<li class="btn btn-inverse control-button previous" role="prev">
	<span class="icon-fast-backward icon-white"></span>
</li>
<li class="btn btn-inverse control-button stop" role="stop">
	<span class="icon-stop icon-white"></span>
</li>
<li class="btn btn-inverse control-button play" role="play">
	<span class="icon-play icon-white"></span>
</li>
<li class="btn btn-inverse control-button next" role="next">
	<span class="icon-fast-forward icon-white"></span>
</li>