<?php $currentTrackDetails = $this->getCurrentTrackDetails() ?>

<div class="title-container">
    <span class="progressbar"></span>
    <h2 class="no-user-select">Now Playing</h2>
</div>
<div class="player-container">
    <a href="<?php echo $this->getStreamExternalUrl() ?>">
        <span class="btn btn-inverse btn-stream-link">
            <span class="icon-share icon-white"></span>
        </span>
    </a>
    <div id="player">Loading the player...</div>
</div>
<div class="row-fluid" id="currentlyplaying-box">
    <div class="cover span2">
        <?php include __DIR__ . '/cover.phtml'; ?>
    </div>
    <div class="container-fluid span10">
        <?php if ($currentTrackDetails): ?>
        <div class="detail-container pos-fullpath">
        	<span class="pos label no-user-select">#<?php echo $currentTrackDetails['pos'] ?></span>
        	<span class="value"><?php echo $currentTrackDetails['fullpath'] ?></span>
        </div>
        <div class="first-row">
            <div class="detail-container artist">
            	<span class="label no-user-select">
            	   <span class="icons">
            	       <?php if ($url = $this->getSearchLinkUrl('artist')): ?><a class="searchlink" target="_blank" href="<?php echo $url ?>"></a><?php endif; ?>
        	       </span>
        	       Artist
    	       </span>
                <span class="value"><?php echo JaddleWeb::htmlText($currentTrackDetails['artist'], true) ?></span>
            </div>
            <div class="detail-container album">
            	<span class="label no-user-select">
            	   <span class="icons">
            	       <?php if ($url = $this->getSearchLinkUrl('album')): ?><a class="searchlink" target="_blank" href="<?php echo $url ?>"></a><?php endif; ?>
        	       </span>
        	       Album
    	       </span>
            	<span class="value"><?php echo JaddleWeb::htmlText($currentTrackDetails['album'], true) ?></span>
            </div>
        </div>
        <div class="second-row">
            <div class="detail-container track">
            	<span class="label no-user-select">Track</span>
                <span class="value"><?php echo $currentTrackDetails['track'] ?></span>
            </div>
            <div class="detail-container title">
            	<span class="label no-user-select">
            	   <span class="icons">
                	   <?php if ($url = $this->getSearchLinkUrl('title')): ?><a class="searchlink" target="_blank" href="<?php echo $url ?>"></a><?php endif; ?>
                	   <?php if ($lyrics = $this->getLyrics()): ?><a class="lyricslink tooltiped" target="_blank" href="<?php echo $lyrics['url'] ?>" data-toggle="tooltip" data-placement="top" data-container="body" title="<?php echo $lyrics['lyrics'] ?>"></a><?php endif; ?>
            	   </span>
            	   Title
        	   </span>
                <span class="value"><?php echo JaddleWeb::htmlText($currentTrackDetails['title'], true) ?></span>
            </div>
        </div>
        <?php else: ?>
        <div class="alert">
            <span class="nocurrenttrack">It seems MPD isn't currently playing anything...</span>
        </div>
        <?php endif; ?>
    </div>
</div>

<!-- Lyrics Box -->
<div id="lyricsviewer-modal" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Lyrics Viewer</h3>
    </div>

    <div class="modal-body">
        <div class="progress progress-striped active loading">
            <div class="bar" style="width: 100%;">Loading lyrics, please wait...</div>
        </div>
    </div>

    <div class="modal-footer">
        <a href="#" class="btn close-btn">Close</a>
    </div>
</div>