<?php $tracks = $this->getTracksHistory() ?>

<?php if (! isset($tracks[0])): ?>
<div class="alert alert-info">
	<span class="tracks-grid-empty">Tracks history is empty.</span>
</div>

<?php else: ?>

<?php include JADDLE_TEMPLATES_DIR . '/tracksgrid/pager.phtml'; ?>
<table id="full_log_table" class="table table-striped table-bordered table-condensed table-hover data-table tracks-grid sortable">
	<caption>Tracks History</caption>
	<thead>
		<tr>
		<?php foreach($tracks[0] as $columnName => $data): ?>
			<?php if ($columnName == 'id') continue; ?>
			<th class="<?php echo $columnName ?>"><?php echo JaddleWeb::htmlText($columnName) ?></th>
		<?php endforeach; ?>
		</tr>
	</thead>
	<tbody>
	<?php $i = 1; foreach($tracks as $track): ?>
		<?php if (false && $i++ % 20 == 0): //DISABLED ?>
		<tr>
			<?php foreach($tracks[0] as $columnName => $data): ?>
			<?php if ($columnName == 'id') continue; ?>
			<th class="<?php echo $columnName ?>"><?php echo JaddleWeb::htmlText($columnName) ?></th>
			<?php endforeach; ?>
		</tr>
		<?php endif; ?>
		<tr>
		<?php foreach($track as $columnName => $data): ?>
			<?php if ($columnName == 'id') continue; ?>
			<td class="<?php echo $columnName ?>"><?php echo JaddleWeb::htmlText(JaddleWeb::formatTrackData($columnName, $data)) ?></td>
		<?php endforeach; ?>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
<?php include JADDLE_TEMPLATES_DIR . '/tracksgrid/pager.phtml'; ?>
<?php endif; ?>